### PR TITLE
[New Component] A rebass-friendly version of hidden-styled

### PR DESCRIPTION
**Pull request by zabute**
[hidden-styled](https://github.com/jxnblk/hidden-styled) works great with rebass but has a  few missing features:
  - Breakpoints cannot be configured via the theme.
  - Not possible to control what gets rendered with an ```is``` prop.
  - No possible to use styled-system;

This PR introduces a new Component, Hide, which is a slightly modified version of ```hiidden-styled``` to add said missing features.

PR Includes docs (markdown demo) and a test case.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Happy to see this, I talked with @jxnblk about that on Twitter:
https://twitter.com/Kikobeats/status/971480275107663873

I implemented a slightly different version, using breakpoints array position as API:
https://gist.github.com/Kikobeats/0dbda3ec8154fa942dc47d36504681c6

**Comment by zabute** [comment]
I too like your version of the  API better. ```styled-system``` compatibility is still missing, though. If you are going to make a PR from that gist then I'll close this.

**Comment by Kikobeats** [comment]
feel free to copy/paste and update this PR 👍

**Comment by ferMartz** [comment]
:raised_hands: Thanks @Kikobeats. Great snippet!

**Comment by jxnblk** [comment]
Thanks for this! I do want to think about the API for this a little more, and it might make sense to have this update in hidden-styled, which I'm considering moving into the grid-styled repo as a subpackage

**Comment by jxnblk** [comment]
Thanks again for putting this together! Was helpful for thinking about how to approach this, but I'm going to close this PR out in favor of #441

**Pull request closed without merging**
