### PR TITLE
Base pure render class

### PR DESCRIPTION
**Pull request by jxnblk**
- Changes the Base component from a stateless functional component to a class
- Adds a `pureRender` option to the rebass context to allow use of `PureRenderMixin`
- Adds a `baseRef` prop as proposed in #72

Curious what @contra, @justingreenberg, et al. think of this approach.

### CODE REVIEW

**Comment by contra** [comment]
@jxnblk Any info on why pure rendering went from being mandatory to optional?

**Comment by phated** [comment]
@contra there was never pure rendering.  Stateless components aren't purely rendered in react currently.  There's an open issue where they are discussing it but there are a lot of naysayers.  Pretty sure this PR is actually making it available.

**Comment by contra** [comment]
@phated Got a link to that issue?

**Comment by justingreenberg** [comment]
@contra see: https://github.com/facebook/react/pull/6914

**Comment by jxnblk** [comment]
This is interesting. Not sure if that means I should hold off on this PR or just update the Base component when/if `PureComponent` is in React...

**Pull request merged**
