### PR TITLE
Bump styled-system to v1.0.0-15

### PR DESCRIPTION
**Pull request by smith-kyle**

### CODE REVIEW

**Comment by smith-kyle** [comment]
On second thought, I'm seeing some react warnings for the themes passed to provider

**Comment by smith-kyle** [comment]
Ok, those prop types have been changed. But I wasn't sure whether to allow arrays of strings to be passed to `breakpoints`. Do break points run through this function?

https://github.com/jxnblk/styled-system/blob/master/src/space.js#L41-L52

**Comment by smith-kyle** [comment]
I just pushed a fix, I had passed separate arguments to `oneOfType` rather than an array. This PR has turned into a bit of a mess but to my knowledge it's now actually ready for review 😄

**Comment by jxnblk** [comment]
Thanks for this, but #342 included an update to the latest styled-system

**Pull request closed without merging**
