### PR TITLE
Add a disabled class to a button if it's disabled

### PR DESCRIPTION
**Pull request by ddispaltro**
So you can do special things with `:hover`, etc.

### CODE REVIEW

**Comment by jxnblk** [comment]
I'm not sure I understand the intent here. What does this provide that the HTML disabled attributed doesn't already?

**Comment by ddispaltro** [comment]
I modeled it after, https://github.com/jxnblk/rebass/blob/master/src/Textarea.js#L51-L53 and I am guessing the intention with this code is to allow for styles like:

```css
.Button:hover {
  box-shadow: inset 0 0 0 999px rgba(0, 0, 0, .25);
}

.Button.isDisabled:hover  {
  box-shadow: none;
}
```

**Comment by jxnblk** [comment]
Right, TBH I'm not sure why I added a special disabled class to the form elements...

For the Button, you should be able to use `.Button:disabled:hover` though...

**Comment by ddispaltro** [comment]
Good point, Ill close then.

**Pull request closed without merging**
