### PR TITLE
Update dependencies (React 15 → 16.2)

### PR DESCRIPTION
**Pull request by lachlanjc**
Update to React 16, the new Grid Styled, etc, and docs to Webpack 3.6. All tests still pass and docs load correctly.

### CODE REVIEW

**Comment by adamellsworth** [comment]
We have a break change because of this, though I'm not sure if it's because of our webpack config or not: https://github.com/jxnblk/grid-styled/issues/52

**Comment by lachlanjc** [comment]
@adamellsworth Made a PR to fix this! https://github.com/jxnblk/grid-styled/pull/56

**Comment by ambethia** [comment]
Anything I can help with that's blocking this PR?

**Comment by lachlanjc** [comment]
@ambethia Don’t think so! @jxnblk is just busy

**Comment by jxnblk** [comment]
Thanks for this! To update the snapshots, run `npm t -- -u` then commit the changes. If Travis is still failing after that I can take a look

**Comment by lachlanjc** [comment]
@jxnblk Everything’s good to go!

**Comment by lachlanjc** [comment]
@jxnblk Ping :)

**Comment by lachlanjc** [comment]
@jxnblk Updated again to React 16.1.1, tests pass 💯

**Comment by lachlanjc** [comment]
@jxnblk Updated to React 16.2, and docs as well, tests still pass 😺

**Comment by lachlanjc** [comment]
@jxnblk Ping 😀

**Comment by maxdeviant** [comment]
@jxnblk Sorry to bump this again, but any change we could get this merged/released?

**Comment by ambethia** [comment]
I think this might be why we're not seeing a lot of action on this: https://compositor.io/lab/

**Comment by lachlanjc** [comment]
@ambethia for sure :)

**Comment by epilande** [comment]
Maybe it's time for this project to have more maintainers..but that's really up to @jxnblk.

**Comment by jxnblk** [comment]
Sorry for the delay, but thanks for this @lachlanjc!

**Pull request merged**
