### PR TITLE
Adds support for specifying an activeColor for SequenceMaps

### PR DESCRIPTION
**Pull request by jpiv**

### CODE REVIEW

**Comment by jxnblk** [comment]
How is this any different than the `color` prop?

**Comment by jxnblk** [comment]
Ah, I think I see what you're doing here. I'd prefer to repurpose the color prop if that makes sense. Would need to look over the code again to refresh my memory

**Comment by jpiv** [comment]
Repurposing the color prop makes sense to me, right now the color prop will make the SequenceMapStep whatever color you specify in all scenarios.  The functionality I was looking for was specifying colors for when a SequenceMapStep is active.  Like this. SequenceMap

**Comment by jxnblk** [comment]
Yeah that's what I was remembering. I'd be down to change that behavior, where color prop sets active color and maybe the default color is set in SequenceMapStep based on a global

**Comment by jpiv** [comment]
PR updated - color prop now specifies the active color and if none is specified falls back to primary config color `color || colors.primary`

**Comment by jxnblk** [comment]
Haven't checked in browser yet, but where does the default/gray color come from?

**Comment by jpiv** [comment]
SequenceMapStep's color is set to `currentColor` and SequenceMap is getting created with a style of `colors.gray` from the config, so SequenceMapStep is also taking on the color gray.

**Comment by jxnblk** [comment]
I think I misunderstood the original intent of this. I think `activeColor` actually makes more sense as a prop for the SequenceMap component. The current behavior seems a little confusing. Also, if you'd still like to make this change, can you add a comment to the propTypes for documentation purposes?

**Pull request closed without merging**
